# Generated by Django 4.2 on 2026-06-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schooldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#4AA3DF', max_length=7)),
                ('secondary_color', models.CharField(default='#2C7BB6', max_length=7)),
                ('accent_color', models.CharField(default='#F4A460', max_length=7)),
                ('font_family', models.CharField(default='Open Sans', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
