# Generated by Django 4.2 on 2026-07-06 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_remove_attendance_add_mpesa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['academic_year__name', 'name', 'section'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['class_room__name', 'name']},
        ),
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'headteacher']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_led', to=settings.AUTH_USER_MODEL, verbose_name='Class teacher'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='section',
            field=models.CharField(blank=True, max_length=10, verbose_name='Stream'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'headteacher']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('class_room', 'code')},
        ),
    ]
