# Generated by Django 4.2 on 2026-07-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_first_name_alter_student_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees', '0003_remove_attendance_add_mpesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], default='mtn', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('transaction_reference', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('result_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feestructure')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('mobile_money', 'Mobile Money')], default='cash', max_length=20),
        ),
        migrations.DeleteModel(
            name='MpesaTransaction',
        ),
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_money_transaction', to='fees.payment'),
        ),
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_transactions', to='students.student'),
        ),
    ]
