# Generated by Django 4.2 on 2026-06-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.timeslot'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term'),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('class_room', 'time_slot', 'term')},
        ),
    ]
