# Generated by Django 4.2 on 2026-06-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schooltheme'),
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='subject',
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.exam'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
